/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 34.1.0 Tue Jun  9 19:59:44 2020.
 */

#include <string.h>

#include "per_2021.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int per_2021_main_heartbeat_pack(
    uint8_t *dst_p,
    const struct per_2021_main_heartbeat_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->main_heartbeat, 0u, 0x01u);

    return (8);
}

int per_2021_main_heartbeat_unpack(
    struct per_2021_main_heartbeat_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->main_heartbeat = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

bool per_2021_main_heartbeat_main_heartbeat_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int per_2021_main_state_change_pack(
    uint8_t *dst_p,
    const struct per_2021_main_state_change_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->main_car_state, 0u, 0x07u);

    return (8);
}

int per_2021_main_state_change_unpack(
    struct per_2021_main_state_change_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->main_car_state = unpack_right_shift_u8(src_p[0], 0u, 0x07u);

    return (0);
}

bool per_2021_main_state_change_main_car_state_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

int per_2021_pdl_heartbeat_pack(
    uint8_t *dst_p,
    const struct per_2021_pdl_heartbeat_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->pdl_heartbeat, 0u, 0x01u);

    return (1);
}

int per_2021_pdl_heartbeat_unpack(
    struct per_2021_pdl_heartbeat_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->pdl_heartbeat = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

bool per_2021_pdl_heartbeat_pdl_heartbeat_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int per_2021_dsh_heartbeat_pack(
    uint8_t *dst_p,
    const struct per_2021_dsh_heartbeat_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->dsh_heartbeat, 0u, 0x01u);

    return (1);
}

int per_2021_dsh_heartbeat_unpack(
    struct per_2021_dsh_heartbeat_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->dsh_heartbeat = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

bool per_2021_dsh_heartbeat_dsh_heartbeat_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int per_2021_dsh_buttons_pack(
    uint8_t *dst_p,
    const struct per_2021_dsh_buttons_t *src_p,
    size_t size)
{
    uint8_t dsh_start_button;

    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dsh_start_button = (uint8_t)src_p->dsh_start_button;
    dst_p[0] |= pack_left_shift_u8(dsh_start_button, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->dsh_traction_mode, 1u, 0x06u);

    return (1);
}

int per_2021_dsh_buttons_unpack(
    struct per_2021_dsh_buttons_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t dsh_start_button;

    if (size < 1u) {
        return (-EINVAL);
    }

    dsh_start_button = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    if ((dsh_start_button & (1u << 0)) != 0u) {
        dsh_start_button |= 0xfeu;
    }

    dst_p->dsh_start_button = (int8_t)dsh_start_button;
    dst_p->dsh_traction_mode = unpack_right_shift_u8(src_p[0], 1u, 0x06u);

    return (0);
}

bool per_2021_dsh_buttons_dsh_start_button_is_in_range(int8_t value)
{
    return ((value >= -1) && (value <= 0));
}

bool per_2021_dsh_buttons_dsh_traction_mode_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int per_2021_pdl_throttle_pack(
    uint8_t *dst_p,
    const struct per_2021_pdl_throttle_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u16(src_p->pdl_throttle_position_a, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->pdl_throttle_position_a, 8u, 0x0fu);
    dst_p[1] |= pack_left_shift_u16(src_p->pdl_throttle_position_b, 4u, 0xf0u);
    dst_p[2] |= pack_right_shift_u16(src_p->pdl_throttle_position_b, 4u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->pdl_break_position_a, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->pdl_break_position_a, 8u, 0x0fu);
    dst_p[4] |= pack_left_shift_u16(src_p->pdl_break_position_b, 4u, 0xf0u);
    dst_p[5] |= pack_right_shift_u16(src_p->pdl_break_position_b, 4u, 0xffu);

    return (7);
}

int per_2021_pdl_throttle_unpack(
    struct per_2021_pdl_throttle_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    dst_p->pdl_throttle_position_a = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->pdl_throttle_position_a |= unpack_left_shift_u16(src_p[1], 8u, 0x0fu);
    dst_p->pdl_throttle_position_b = unpack_right_shift_u16(src_p[1], 4u, 0xf0u);
    dst_p->pdl_throttle_position_b |= unpack_left_shift_u16(src_p[2], 4u, 0xffu);
    dst_p->pdl_break_position_a = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->pdl_break_position_a |= unpack_left_shift_u16(src_p[4], 8u, 0x0fu);
    dst_p->pdl_break_position_b = unpack_right_shift_u16(src_p[4], 4u, 0xf0u);
    dst_p->pdl_break_position_b |= unpack_left_shift_u16(src_p[5], 4u, 0xffu);

    return (0);
}

bool per_2021_pdl_throttle_pdl_throttle_position_a_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

bool per_2021_pdl_throttle_pdl_throttle_position_b_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

bool per_2021_pdl_throttle_pdl_break_position_a_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

bool per_2021_pdl_throttle_pdl_break_position_b_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}
